backend:
  name: github
  repo: dadatoa/nebulous-nadir
  branch: develop

media_library:
  name: cloudinary
  config:
    cloud_name: daz7gamgu
    api_key: 276326737381514
# media_folder: static/images/uploads

# Publish mode
publish_mode: editorial_workflow

# Slug - personnalisation des liens
slug:
  clean_accents: true

collections:
  # recettes
  - name: "recipes"
    label: "recette"
    folder: "src/pages/recipes/"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/MarkdownPostLayout.astro"}
      - { label: "Title", name: "title", widget: "string", hint: "" }
      - { label: "Monochrome", name: "monochrome", widget: "boolean", default: false }
      - { label: "Camera", name: "camera", widget: "string"}
      - { label: "Capteur", name: "sensor", widget: "string"}
      - { label: "simualtion", name: "film_sim", widget: "string"}
      - { label: "Dynamic Range", name: "dynamic_range", widget: "string"}
      - { label: "Color Chrome", name: "color_chrome", widget: "string", required: false }
      - { label: "Color Chrome FX blue", name: "color_chromeFXblue", widget: "string", required: false }
      -  label: "Grain"
         name: "grain"
         widget: "object"
         collapse: "false"
         fields:
          - { label: "Effet", name: "effect", widget: "string" }
          - { label : "Taille", name: "size", widget: "string" }
      - label: "Balance des blancs"
        name: "white_balance"
        widget: "object"
        collapse: "false"
        fields:
          - { label: "Preset", name: "preset", widget: "string" }
          - { label: "Rouge", name: "red", widget: "number", value_type: "int", min: -9, max: 9, defaul: 0 }
          - { label: "Bleu", name: "blue", widget: "number", value_type: "int", min: -9, max: 9, defaul: 0 }
      - { label: "Tons clairs", name: "highlights", widget: "number", value_type: "int", min: -4, max: 4, defaul: 0 }
      - { label: "Ombres", name: "shadows", widget: "number", value_type: "int", min: -4, max: 4, defaul: 0 }
      - { label: "Couleur", name: "color", widget: "number", value_type: "int", min: -4, max: 4, defaul: 0 }
      - { label: "Sharpness", name: "sharpness", widget: "number", value_type: "int", min: -4, max: 4, defaul: 0 }
      - { label: "Réduction du bruit", name: "noise_reduction", widget: "number", value_type: "int", min: -4, max: 4, defaul: 0 } 
      - { label: "Clarity", name: "clarity", widget: "number", value_type: "int", min: -4, max: 4, required: false }
      - { label: "Créateur", name: "chef", widget: "string" }
      - label: "source"
        name: "source"
        widget: "object"
        required: false
        collapse: "true"
        fields:
          - { label: "type", name: "type", widget: "string", required: false }
          - { lable: "url", name: "url", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }